### ISSUE TITLE
Change minimum limit in terms of stock quantity

### ISSUE THREAD

**Issue by adnanalneon** [pluginever/wc-min-max-quantities#69]
If a certain product has stock, there would be an option that can be deployed on the stock quantity limit. For example, if a product has a stock quantity of 80, the minimum product quantity limit would be 80. As the stock quantity goes down, the quantity limit will automatically go down. That means if the stock is 75, the quantity limit will be 75, if the stock quantity is 74, the product quantity limit will be 74. 

As the stock decreases, the minimum product quantity limit will also decrease automatically. The feature will be active on the single product page as well as the cart page.

**Comment by sudipto-me** [comment]
This is already fixed.
