### ISSUE TITLE
New feature - Add a reset button

### ISSUE THREAD

**Issue by gkibria69** [pluginever/wc-min-max-quantities#8]
There are different levels where the user can set min-max rules. It is easy to get confused marking which rule is currently in action. So I think to add a reset button to erase every rule is an excellent option to avoid those situations.

**Comment by mahedihasannoman** [comment]
Will it reset all global & product level rules or just global rules?

**Comment by gkibria69** [comment]
Yes, my suggestion is to reset all global and product level rules.
